import Head from "next/head";
import React from "react";

type PageHeadProps = {
    title: string
}

export function PageHead(props: PageHeadProps) {
    return <Head>
        <title>{props.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
}